### PR TITLE
Finish Base Game Features

### LINKED ISSUE #17: Add Battle Mechanism
This is probably going to be the second to last issue:

- [x] implement the remaining functions that are necessary to play the game (`make_move`, etc.)
- [x] print move table
- [x] catch invalid user input
- [x] ensure that `configure_move_set` generates at least one move of type `MoveType::ATTACK`
- [x] balance difficulty
- [x] add the main event loop in `main.cpp`; add this point the game should be about done

Once this PR is merged test the game thoroughly and return helpful error messages in case something goes wrong.

### PR DESCRIPTION
**Pull request by hentai-chan**
Closes #17 . The game should now have entered a playable state.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -23,14 +17,24 @@ int main()
...
-		std::cout << "TODO: init game loop" << '\n';
-		sleep(1000);
-		clear_screen();
+		while (player.hp > 0 && ai.hp > 0)
+		{
+			player.make_move(ai, print_frame(player, ai));
+
+			if (ai.hp > 0)
+			{
+				sleep(1000);
```
Comment (karnkaul) [inline src/main.cpp]: Just FYI: using `chrono` and `thread` (and `chrono_literals`): `std::this_thread::sleep_for(1000ms)`

File: src/models.hpp [hunk 2]
```diff
@@ -29,9 +29,9 @@ struct Move
 
 enum class Difficulty
 {
-	EASY,
-	MODERATE,
-	HARD
+	EASY = 1,
```
Comment (karnkaul) [inline src/models.hpp]: By convention, enum values start from 0; is there a good reason this does not? (Adding `INVALID` as `0` and the default might make sense.)

File: src/utils.cpp [hunk 3]
```diff
@@ -25,6 +18,17 @@ void sleep(int ms)
 	std::this_thread::sleep_for(std::chrono::milliseconds(ms));
 }
 
+void slow_print(std::string str, int ms)
```
Comment (karnkaul) [inline src/utils.cpp]: `str` should be a const ref / `string_view`

File: src/utils.cpp [hunk 4]
```diff
@@ -25,6 +18,17 @@ void sleep(int ms)
...
+{
+	for (const char& c : str)
```
Comment (karnkaul) [inline src/utils.cpp]: Reference to `char` is actually worse than a copy (8 bytes vs 1, + pointer deref cost if any)

File: src/utils.hpp [hunk 5]
```diff
@@ -3,12 +3,15 @@
...
 #include <iostream>
+#include <limits>
+#include <numeric>
 #include <random>
 #include <type_traits>
 #include <vector>
 
 namespace utils
 {
+static constexpr long long str_max{std::numeric_limits<std::streamsize>::max()};
```
Comment (karnkaul) [inline src/utils.hpp:14]: `static` in headers is not a good idea; here you're ok because it's a constant, otherwise it would be UB

File: src/utils.cpp [hunk 6]
```diff
@@ -115,6 +119,24 @@ void print_enum_table(std::vector<std::string> table, std::string header)
 	std::cout << horizontal_line << '\n';
 }
 
+int validate_user_input(std::vector<std::string> table, std::string header)
```
Comment (karnkaul) [inline src/utils.cpp:120]: `table` and `header` should be const refs

**Review by karnkaul — CHANGES_REQUESTED** [review]

File: src/main.cpp (hunk 1 above)
Comment (karnkaul) [reply src/main.cpp]: Okay so your `utils` function already does that; then have it take a `duration` 
(would need to be a template, otherwise just take a specific unit, like `milliseconds`) instead of a raw integer. 

Why? Because looking at this function call I have no idea what the unit is.

File: src/models.hpp (hunk 2 above)
Comment (hentai-chan) [reply src/models.hpp:32]: There actually is a good reason for that! It's because of this line:

```cpp
this->level = utils::random_range<int>(max * static_cast<int>(difficulty) - min, max * static_cast<int>(difficulty));
```

I could add `INVALID` as another state at place it at the top, so that I don't have to adjust the formula. The `Pokemon` constructor takes `MODERATE` as a default argument, so it's pretty much impossible that anywhere else I'd have account for the case that `difficulty` is never set, but it does no harm in adding it to the enum so I will probably just do it.

File: src/utils.cpp (hunk 6 above)
Comment (hentai-chan) [reply src/utils.cpp:122]: Not quite `const` because I called `lower()` and `upper()` on the `table` and `header`, respectively.  But here I could get away with passing the header already in caps, so it ended up being const-ref anyway.

File: src/anim.cpp [hunk 7]
```diff
@@ -44,7 +44,7 @@ void print_splash_screen(const std::filesystem::path& assets_dir)
 	for (const char& c : "copyright (c) 2021 cpp-gamedev")
 	{
 		std::cout << c;
-		utils::sleep(100);
+		utils::sleep(std::chrono::milliseconds{50});
```
Comment (karnkaul) [inline src/anim.cpp]: If you use `using namespace std::chrono_literals`, you can use `50ms` here directly.

**Review by karnkaul — APPROVED** [review]
